### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vjuagar** [snight1983/chia-rosechain#6]
**Describe the bug**

Hello, I have installed the program and it gives me errors, it reads the plots and gives them to me for tests found but they do not reach the portfolio, the address appears that of chia instead of the chiarose.  even if I change it, it is corrected but when I win a reward it never reaches the portfolio.![image](https://user-images.githubusercontent.com/26313162/122851402-2db8fb80-d30f-11eb-9ef9-2d2afc07844d.jpeg)

OS: Windows 64

**Comment by snight1983** [comment]
The xch address prefix can be modified in the configuration file, 
 C:\Users\51171\.chiarose\mainnet\config\config.yaml   
mainnet:
  address_prefix: xch
to
mainnet:
  address_prefix: xcr

**Comment by snight1983** [comment]
In addition, due to the excessive modification of the initial difficulty, a large number of proofs with complex conditions will be discovered, but after many found proofs have competed, only one proof will get the block reward. (The address prefix does not affect the distribution of rewards and transfers, it is just a display O(∩_∩)O)

**Comment by Nitrooo** [comment]
> The xch address prefix can be modified in the configuration file,
> C:\Users\51171.chiarose\mainnet\config\config.yaml
> mainnet:
> address_prefix: xch
> to
> mainnet:
> address_prefix: xcr

So, what does that mean? Are generated addresses wrong? This seems like a 5 minutes fix, why is your code still broken?

**Comment by snight1983** [comment]
O(∩_∩)O
